// Properties Reference
// Styles: Runner, Basketball, Skate, low_Minimal, Chucks, slip_On, Sock
// Occasion: Casual, Going Out, Active
// Materials: Synthetic, Canvas, Suede, Leather

const sneakers = [
    {
        brand: "Nike",
        name: "Space Hippie 04",
        price: 130,
        // how can i have multiple, seperately referenceable entries?
        material: 'Synthetic',
        color: 'grey',
        occasion: 'Active',
        silohuette: 'Runner',
        // source: '?' doesn't appear to be easily accessible
        image: 'images/0001.jpg',
        link: 'https://www.nike.com/t/space-hippie-04-mens-shoe-gGWDLk/CZ6398-002?nikemt=true&cp=96413943330_search_%7cPRODUCT_GROUP%7cGOOGLE%7c71700000041489782%7cAll_X_X_X_X-Device_X_Nike-Clearance_X%7c%7cc&gclid=Cj0KCQjwmIuDBhDXARIsAFITC_7aVU7xKEntm8ZG8oHtFXgdkbxl4B6j8JYxGhoSMxdvEIsm2MLOIlcaAn_zEALw_wcB&gclsrc=aw.ds',
    },
    {
        brand: "Balenciaga",
        name: "Triple S Clear Sole",
        price: 1090,
        material: "Synthetic",
        color: "Black",
        occasion: 'Going Out',
        silohuette: 'Runner',
        image: 'images/0002.jpg',
        link: 'https://www.balenciaga.com/en-us/triple-s-clear-sole-black-544351W2FB11000.html', 
    },
    {
        brand: "Off-White",
        name: "OUT OF OFFICE",
        price: "515",
        material: "Cotton",
        color: "Beige",
        occasion: 'Casual',
        silohuette: 'Skate',
        image: 'images/0003.jpg',
        link: 'https://www.off---white.com/en-us/shopping/off-white-womens-out-of-office-ooo-sneakers-16254218', 
    },
    {
        brand: "Golden Goose",
        name: "Super-Star",
        price: 560,
        material: "Suede",
        color: "Brown",
        occasion: 'Going Out',
        silohuette: 'low-Minimal',
        image: 'images/0004.jpg',
        link: 'https://www.goldengoose.com/us/en/leopard-print-suede-super-star-sneakers-cod-GWF00101.F001472.81116.html', 
    },
    {
        brand: "New Balance",
        name: "993",
        price: 184.99,
        material: "Synthetic",
        color: "Grey",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0005.jpg',
        link: 'https://www.newbalance.com/pd/mens-made-in-us-993/MR993V1-M.html', 
    },
    {
        brand: "Adidas",
        name: "Stan Smith",
        price: 85,
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'low-Minimal',
        image: 'images/0006.jpg',
        link: 'https://www.adidas.com/us/stan-smith-shoes/FX5502.html', 
    },
    {
        brand: "Nike",
        name: "Blazer Mid '77",
        price: 100,
        material: "Leather",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Basketball',
        image: 'images/0007.jpg',
        link: 'https://www.nike.com/t/blazer-mid-77-essential-womens-shoe-25h71W/CZ1055-114?nikemt=true&cp=71606177307_search_%7CPRODUCT_GROUP%7CGOOGLE%7C71700000041489779%7CAll_X_X_X_X-Device_X_Nike-FullPrice_X%7C%7Cc&gclsrc=aw.ds&&gclid=CjwKCAjwjbCDBhAwEiwAiudByxnOZVR-u59tR4I8rEl8uHmlTXtxWTvaH7uuImenppevmqtN-_NXnBoCN7UQAvD_BwE&gclsrc=aw.ds', 
    },
    {
        brand: "Vans",
        name: "Old Skool",
        price: 60,
        material: "Canvas",
        color: "Black",
        occasion: 'Casual',
        silohuette: 'Skate',
        image: 'images/0008.jpg',
        link: 'https://www.vans.com/shop/old-skool-black-white?utm_id=go_cmp-191532173_adg-26624222573_ad-95842386413_pla-866008078493_dev-c_ext-_prd-700053803770_mca-8181713_sig-CjwKCAjwjbCDBhAwEiwAiudByzJZruajq9SjI2OWs6qa5fyyVYE1I9wg2zufqghhya013cPJtkSZyhoC1SUQAvD_BwE&utm_source=google&gclid=CjwKCAjwjbCDBhAwEiwAiudByzJZruajq9SjI2OWs6qa5fyyVYE1I9wg2zufqghhya013cPJtkSZyhoC1SUQAvD_BwE', 
    },
    {
        brand: "Converse",
        name: "Chuck Taylor All Star",
        price: 55,
        material: "Canvas",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Chucks',
        image: 'images/0009.jpg',
        link: 'https://www.converse.com/shop/p/chuck-taylor-all-star-unisex-low-top-shoe/M7652.html?dwvar_M7652_color=optical%20white&styleNo=M7652&cgid=womens-best-sellers', 
    },
    {
        brand: "Air Jordan",
        name: "Jordan 1 Retro High",
        price: 160,
        material: "Leather",
        color: "Red",
        occasion: 'Going Out',
        silohuette: 'Basketball',
        image: 'images/0010.jpg',
        link: 'https://stockx.com/air-jordan-1-retro-high-satin-black-toe-w', 
    },
    {
        brand: "Nike",
        name: "Air Max 90",
        price: 120,
        material: "Synthetic",
        color: "Pink",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0011.jpg',
        link: '', 
    },
    {
        brand: "Reebok",
        name: "Club C 85",
        price: 70,
        material: "Leather",
        color: "White",
        occasion: 'Casual',
        silohuette: 'low-Minimal',
        image: 'images/0012.jpg',
        link: 'https://www.reebok.com/us/club-c-85-model-vintage-womens-shoes/BS8242.html', 
    },
    {
        brand: "Asics",
        name: "GEL-MC Plus",
        price: "110",
        material: "Textile",
        color: "Grey",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0013.jpg',
        link: 'https://www.asics.com/us/en-us/gel-mc-plus/p/ANA_1201A193-020.html?size=12&width=Standard', 
    },
    {
        brand: "Yeezy",
        name: "Boost 700 Wave Runner",
        price: "240",
        material: "Textile",
        color: "Multi",
        occasion: 'Going Out',
        silohuette: 'Runner',
        image: 'images/0014.jpg',
        link: 'https://www.flightclub.com/yeezy-boost-700-mgsogr-cwhite-cblack-802501?utm_source=google_int&utm_medium=google_shopping_int&utm_campaign=11752349677_111935357657&utm_content=483318311964_&utm_term=191040706868&gclid=CjwKCAjwjuqDBhAGEiwAdX2cj06Pt43XfcI7HT4uIV6tgdRHD91NZ6ShRW2v-c6-YsHW9hWGwktVVhoCKkAQAvD_BwE', 
    },
    {
        brand: "Nike",
        name: "Air Force 1",
        price: "90",
        material: "Leather",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Basketball',
        image: 'images/0015.jpg',
        link: 'https://www.nike.com/t/air-force-1-07-mens-shoe-5QFp5Z/CW2288-111?nikemt=true&cp=71606177307_search_%7CPRODUCT_GROUP%7CGOOGLE%7C71700000041489779%7CAll_X_X_X_X-Device_X_Nike-FullPrice_X%7C%7Cc&gclsrc=aw.ds&&gclid=CjwKCAjwjuqDBhAGEiwAdX2cj-N0ONpiaeLC1KQIr3-2Ag3mXVCe18npkQOV40wa2odhM26ra6FNPhoCtggQAvD_BwE&gclsrc=aw.ds', 
    },
    {
        brand: "Superga",
        name: "2750 Cotu",
        price: "65",
        material: "Canvas",
        color: "Black",
        occasion: 'Casual',
        silohuette: 'Deck',
        image: 'images/0016.jpg',
        link: 'https://www.superga-usa.com/collections/womens-classic/products/2750-cotu-classic-black-white?variant=22652942254138&', 
    },
    {
        brand: "Common Projects",
        name: "Achilles",
        price: "410",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'low_Minimal',
        image: 'images/0017.jpg',
        link: 'https://www.mrporter.com/en-us/mens/product/common-projects/shoes/low-top-sneakers/original-achilles-leather-sneakers/3024088872901549', 
    },
    {
        brand: "Adidas",
        name: "4D Futurecraft",
        price: "220",
        material: "Textile",
        color: "Black",
        occasion: 'Active',
        silohuette: 'Runner',
        image: 'images/0018.jpg',
        link: 'https://kith.com/collections/mens-footwear/products/aafz2560', 
    },
    {
        brand: "Veja",
        name: "Rio Branco",
        price: "140",
        material: "Textile",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0019.jpg',
        link: 'https://www.veja-store.com/en_us/rio-branco-hexamesh-gravel-nautico-oxford-grey-rb012377.html', 
    },
    {
        brand: "Visvim",
        name: "Skagway Lo",
        price: "720",
        material: "Canvas",
        color: "Green",
        occasion: 'Casual',
        silohuette: 'Chucks',
        image: 'images/0020.jpg',
        link: 'https://shop.visvim.com/0519901001002', 
    },
    {
        brand: "Hender Scheme",
        name: "Manual Industrial Products 22",
        price: "785",
        material: "Leather",
        color: "Brown",
        occasion: 'Going Out',
        silohuette: 'Basketball',
        image: 'image/0021.jpg',
        link: 'https://kith.com/collections/mens-footwear/products/hsmip-22-natural', 
    },
    {
        brand: "Vans",
        name: "Era",
        price: "50",
        material: "Canvas",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Deck',
        image: 'images/0022.jpg',
        link: 'https://www.vans.com/shop/mlx-era-true-white-true-white?utm_id=go_cmp-191532173_adg-26624199053_ad-95842234493_pla-865808573006_dev-c_ext-_prd-EWZBLK_VN%3A000EWZ%3ABLK%3A080%3AM%3A1%3A_mca-8181713_sig-CjwKCAjwjuqDBhAGEiwAdX2cj4sQgfUx1HNrZqViDHY0wnxzcyhbE9k7jFHK4voQ-Uh4mshW5CLsARoC06cQAvD_BwE&utm_source=google&radscid=191532173&gclid=CjwKCAjwjuqDBhAGEiwAdX2cj4sQgfUx1HNrZqViDHY0wnxzcyhbE9k7jFHK4voQ-Uh4mshW5CLsARoC06cQAvD_BwE', 
    },
    {
        brand: "Puma",
        name: "Classic XXI",
        price: "70",
        material: "Suede",
        color: "Red",
        occasion: 'Casual',
        silohuette: 'low-Minimal',
        image: 'images/0023.jpg',
        link: 'https://us.puma.com/en/us/pd/suede-classic-xxi-mens-sneakers/374915.html?dwvar_374915_color=06', 
    },
    {
        brand: "Play Converse",
        name: "Chuck Taylor All Star '70",
        price: "150",
        material: "Canvas",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Chucks',
        image: 'images/0024.jpg',
        link: 'https://shop-us.doverstreetmarket.com/collections/comme-des-garcons-footwear/products/play-converse-chuck-taylor-all-star-70-high-white', 
    },
    {
        brand: "Gucci",
        name: "Ace",
        price: "680",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'low_Minimal',
        image: 'images/0025.jpg',
        link: 'https://www.gucci.com/us/en/pr/women/shoes-for-women/sneakers-for-women/womens-ace-sneaker-with-bee-p-43194202JP09064', 
    },
    {
        brand: "Asics x Vivienne Westwood",
        name: "Gel-Kayano 27 LTX",
        price: "240",
        material: "Textile",
        color: "Black",
        occasion: 'Active',
        silohuette: 'Runner',
        image: 'images/0026.jpg',
        link: 'https://www.asics.com/us/en-us/gel-kayano-27-ltx/p/ANA_1201A115-001.html?width=Standard', 
    },
    {
        brand: "A Bathing Ape",
        name: "Bape Sta",
        price: "202",
        material: "Leather",
        color: "Brown",
        occasion: 'Going Out',
        silohuette: 'Basketball',
        image: 'images/0027.jpg',
        link: 'https://bape.com/collections/all/products/1g70-191-042', 
    },
    {
        brand: "Air Jordan",
        name: "Jordan 4",
        price: "200",
        material: "Suede",
        color: "Taupe",
        occasion: 'Casual',
        silohuette: 'Basketball',
        image: 'images/0028.jpg',
        link: 'https://www.nike.com/my/launch/t/air-jordan-4-taupe-haze', 
    },
    {
        brand: "Adidas",
        name: "NMD_R1",
        price: "140",
        material: "Textile",
        color: "Black",
        occasion: 'Active',
        silohuette: 'Runner',
        image: 'images/0029.jpg',
        link: 'https://www.adidas.com/us/nmd_r1-shoes/FY5727.html?forceSelSize=M%2013%20%2F%20W%2014', 
    },
    {
        brand: "Reebok x Maison Margiela",
        name: "Club C",
        price: "300",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'low_Minimal',
        image: 'images/0030.jpg',
        link: 'https://www.reebok.com/us/maison-margiela-club-c-shoes/H02407.html?cm_sp=SLOT-7.1-_-CP_BRAND_MAISON%20MARGIELA_HOME_%3F-_-PRODUCTLISTGRID-PRODUCT-CARD-_-634599', 
    },
    {
        brand: "Vans",
        name: "Classic Slip-On",
        price: "55",
        material: "Canvas",
        color: "Black and White",
        occasion: 'Casual',
        silohuette: 'slip_On',
        image: 'images/0031.jpg',
        link: 'https://www.vans.com/shop/shoes-classics-classic-slip-on/checkerboard-slip-on-black-off-white-check', 
    },
    {
        brand: "Balenciaga",
        name: "Speed 3.0",
        price: "925",
        material: "Textile",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'Sock',
        image: 'images/0032.jpg',
        link: 'https://www.balenciaga.com/en-us/speed-3.0-sneaker-white-654532W2DN29000.html', 
    },
    {
        brand: "Nike",
        name: "Vapormax Flyknit 3",
        price: "200",
        material: "Textile",
        color: "White",
        occasion: 'Active',
        silohuette: 'Runner',
        image: 'images/0033.jpg',
        link: 'https://www.nike.com/t/air-vapormax-flyknit-3-womens-shoe-ZHCbvC/AJ6910-100', 
    },
    {
        brand: "Common Projects",
        name: "Slip-On",
        price: "400",
        material: "Textile",
        color: "White",
        occasion: 'Casual',
        silohuette: 'slip_On',
        image: 'images/0034.jpg',
        link: 'https://www.mrporter.com/en-us/mens/product/common-projects/shoes/low-top-sneakers/leather-trimmed-nylon-slip-on-sneakers/560971904236873', 
    },
    {
        brand: "Salomon",
        name: "XT-6",
        price: "190",
        material: "Textile",
        color: "Black",
        occasion: 'Active',
        silohuette: 'Runner',
        image: 'images/0035.jpg',
        link: 'https://www.salomon.com/en-us/shop/product/xt-6-adv.html#color=37177', 
    },
    {
        brand: "Adidas",
        name: "Gazelle",
        price: "80",
        material: "Suede",
        color: "Navy",
        occasion: 'Casual',
        silohuette: 'low_Minimal',
        image: 'images/0036.jpg',
        link: 'https://www.adidas.com/us/gazelle-shoes/BB5478.html?forceSelSize=9.5', 
    },
    {
        brand: "Buscemi",
        name: "100mm",
        price: "890",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'Basketball',
        image: 'images/0037.jpg',
        link: 'https://buscemi.com/collections/100mm/products/100mm-bianco', 
    },
    {
        brand: "Reebok",
        name: "RS Curve",
        price: "100",
        material: "Textile",
        color: "Multi",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0038.jpg',
        link: 'https://us.puma.com/en/us/pd/rs-curve-ocean-queen-womens-sneakers/380659.html?dwvar_380659_color=01', 
    },
    {
        brand: "Eytys",
        name: "Doja",
        price: "250",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'low_Minimal',
        image: 'images/0039.jpg',
        link: 'https://eytys.com/product/footwear/sneakers/doja-tumbled-white-sneakers', 
    },
    {
        brand: "Adidas",
        name: "Superstar",
        price: "85",
        material: "Leather",
        color: "White",
        occasion: 'Casual',
        silohuette: 'low_Minimal',
        image: 'images/0040.jpg',
        link: 'https://www.adidas.com/us/superstar-shoes/FV3284.html?clickId=xqQQqtzBGxyLWB8wUx0Mo38cUkB0XeWPs2A-S80&cm_mmc=AdieAffiliates_IR-_-Skimbit%20Ltd.-_-Online%20Tracking%20Link-_-ONLINE_TRACKING_LINK-_-&cm_mmc2=adidas-NA-eCom-Affiliates-_-Skimbit%20Ltd.-_-None-None-US-always-on-None-1801&irgwc=1', 
    },
    {
        brand: "Y-3",
        name: "Orisan",
        price: "400",
        material: "Textile",
        color: "Multi",
        occasion: 'Going Out',
        silohuette: 'Runner',
        image: 'images/0041.jpg',
        link: 'https://www.adidas.com/us/y-3-orisan/FZ4317.html', 
    },
    {
        brand: "Maison Margiela",
        name: "Replica",
        price: "495",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'low_Minimal',
        image: 'images/0042.jpg',
        link: 'https://www.maisonmargiela.com/us/maison-margiela/sneakers-replica_cod11893114hm.html', 
    },
    {
        brand: "Fear of God",
        name: "Sneakers",
        price: "550",
        material: "Suede",
        color: "Black",
        occasion: 'Going Out',
        silohuette: 'Skate',
        image: 'images/0043.jpg',
        link: 'https://www.mrporter.com/en-us/mens/product/fear-of-god/shoes/low-top-sneakers/suede-sneakers/30049528927132705', 
    },
    {
        brand: "Hoka",
        name: "Kaha Low",
        price: "200",
        material: "Textile",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0044.jpg',
        link: 'https://www.hokaoneone.com/women-hiking/kaha-low-gore-tex/1123114.html', 
    },
    {
        brand: "New Balance",
        name: "327",
        price: "89.99",
        material: "Textile",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0045.jpg',
        link: 'https://www.newbalance.com/pd/327/MS327V1-34394.html', 
    },
    {
        brand: "Supreme x Nike",
        name: "SB Dunk Low",
        price: "110",
        material: "Leather",
        color: "Multi",
        occasion: 'Casual',
        silohuette: 'Skate',
        image: 'images/0046.jpg',
        link: 'https://stockx.com/nike-sb-dunk-low-supreme-black?country=US&currencyCode=USD&size=11.5&utm_source=af&utm_medium=imp&utm_campaign=10078&impactSiteId=wU42APRD-xyLUtYwUx0Mo37kUkB0X70Xs2A-S80&clickid=wU42APRD-xyLUtYwUx0Mo37kUkB0X70Xs2A-S80&utm_term=wU42APRD-xyLUtYwUx0Mo37kUkB0X70Xs2A-S80&utm_content=gq.com_530344&irgwc=1', 
    },
    {
        brand: "Onitsuka Tiger",
        name: "Serrano",
        price: "75",
        material: "Textile",
        color: "White",
        occasion: 'Casual',
        silohuette: 'low_Minimal',
        image: 'images/0047.jpg',
        link: 'https://www.onitsukatiger.com/us/en-us/serrano/p/D109L-9049.html?size=5?utm_source=google&utm_medium=pla&CAWELAID=120223060000246066&CAGPSPN=pla&CAAGID=96642872597&CATCI=pla-933704351983&gclid=Cj0KCQjw1PSDBhDbARIsAPeTqre910KvOzOSXJG9RaS3DBPWZuA9VI7P4IIr3nOLaC8jBQyYuAMdvuUaAkuuEALw_wcB', 
    },
    {
        brand: "Novesta",
        name: "Star Dribble",
        price: "65",
        material: "Canvas",
        color: "Black",
        occasion: 'Casual',
        silohuette: 'Chucks',
        image: 'images/0048.jpg',
        link: 'https://www.gonovesta.com/star-dribble-60-black-23-8585014073162-39', 
    },
    {
        brand: "Balenciaga",
        name: "Track.2",
        price: "995",
        material: "Textile",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0049.jpg',
        link: 'https://www.balenciaga.com/en-us/track.2-sneaker-white-568614W2GN19000.html', 
    },
    {
        brand: "Saucony",
        name: "Jazz",
        price: "60",
        material: "Textile",
        color: "Black",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0050.jpg',
        link: 'https://www.saucony.com/en/jazz-original/720026099504.html?utm_source=google&utm_medium=cpc&adpos=&scid=scplp11842M-720026099504&sc_intid=11842M-720026099504&gclid=Cj0KCQjw1PSDBhDbARIsAPeTqrdrBtjTAyXa8mW4S2uIkXX9go4HAUJEiE0NwQ9Ov1nhK9ry-Q4PGXUaAtNzEALw_wcB&gclsrc=aw.ds', 
    },
    {
        brand: "Vans",
        name: "Authentic LX",
        price: "69",
        material: "Canvas",
        color: "Black",
        occasion: 'Casual',
        silohuette: 'Skate',
        image: 'images/0051.jpg',
        link: 'https://www.endclothing.com/us/vans-vault-ua-og-authentic-lx-vn0a4bv94jn1.html', 
    },
    {
        brand: "Reebok x BBC",
        name: "Instapump Fury Boost",
        price: "200",
        material: "Textile",
        color: "Multi",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0052.jpg',
        link: 'https://www.reebok.com/us/bbc-instapump-fury-boost-shoes/GZ5363.html', 
    },
    {
        brand: "New Balance",
        name: "480 BB",
        price: "110",
        material: "Leather",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Basketball',
        image: 'images/0053.jpg',
        link: 'https://www.mileendkicks.ca/us/new-balance-480-bb-480-lwg-white-nvy-red.html', 
    },
    {
        brand: "Clae",
        name: "Bradley",
        price: "150",
        material: "Leather",
        color: "Black",
        occasion: 'Going Out',
        silohuette: 'low_Minimal',
        image: 'images/0054.jpg',
        link: 'https://www.clae.com/collections/the-essentials-line/products/bradley-triple-black-leather', 
    },
    {
        brand: "Filling Pieces",
        name: "Low Top Ripple Napa",
        price: "245",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'low_Minimal',
        image: 'images/0055.jpg',
        link: 'https://www.fillingpieces.com/collections/men-signature-footwear/products/low-top-ripple-basic-nappa-all-white', 
    },
    {
        brand: "Sketchers",
        name: "GOwalk",
        price: "60",
        material: "Textile",
        color: "Grey",
        occasion: 'Casual',
        silohuette: 'slip_On',
        image: 'images/0056.jpg',
        link: 'https://www.skechers.com/men/shoes/skechers-gowalk-max---modulating/216170_CHAR.html', 
    },
    {
        brand: "Converse x Kim Jones",
        name: "Chuck 70",
        price: "160",
        material: "Textile",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'Chucks',
        image: 'images/0057.jpg',
        link: 'https://www.converse.com/shop/p/converse-x-kim-jones-chuck-70-unisex-high-top-shoe/171258MP.html', 
    },
    {
        brand: "Nike",
        name: "Air Max 97",
        price: "170",
        material: "Textile",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0058.jpg',
        link: 'https://www.nike.com/t/air-max-97-womens-shoe-XD9m01/921733-100', 
    },
    {
        brand: "Yeezy",
        name: "Boost 350 V2",
        price: "220",
        material: "Textile",
        color: "Zebra",
        occasion: 'Going Out',
        silohuette: 'Runner',
        image: 'images/0059.jpg',
        link: 'https://stockx.com/adidas-yeezy-boost-350-v2-white-core-black-red?utm_source=af&utm_medium=imp&utm_campaign=10078&impactSiteId=wU42APRD-xyLUtYwUx0Mo37kUkB0Sm3fs2A-S80&clickid=wU42APRD-xyLUtYwUx0Mo37kUkB0Sm3fs2A-S80&utm_term=wU42APRD-xyLUtYwUx0Mo37kUkB0Sm3fs2A-S80&utm_content=one37pm.com_530344&irgwc=1', 
    },
    {
        brand: "All Birds",
        name: "Wool Runner",
        price: "95",
        material: "Textile",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0060.jpg',
        link: 'https://www.allbirds.com/products/mens-wool-runner-fluffs', 
    },
    {
        brand: "Christian Louboutin",
        name: "Boat Man",
        price: "995",
        material: "Textile",
        color: "Black",
        occasion: 'Going Out',
        silohuette: 'slip_On',
        image: 'images/0061.jpg',
        link: 'https://www.mrporter.com/en-us/mens/product/christian-louboutin/shoes/slip-on-sneakers/boat-man-studded-velvet-slip-on-sneakers/46353151654270421', 
    },
    {
        brand: "Air Jordan",
        name: "Jordan III",
        price: "200",
        material: "Leather",
        color: "Black",
        occasion: 'Active',
        silohuette: 'Basketball',
        image: 'images/0062.jpg',
        link: 'https://stockx.com/air-jordan-3-retro-black-cement-2018', 
    },
    {
        brand: "Loewe",
        name: "Flow Runner",
        price: "690",
        material: "Suede",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'Runner',
        image: 'images/0063.jpg',
        link: 'https://www.loewe.com/usa/en/men/shoes/sneakers/flow-runner-in-suede/M816282X10-2100.html?cgid=m_shoes_sneakers&p=4', 
    },
    {
        brand: "Veja",
        name: "Esplar 3-Lock",
        price: "130",
        material: "Leather",
        color: "White",
        occasion: 'Casual',
        silohuette: 'low_Minimal',
        image: 'images/0064.jpg',
        link: 'https://www.veja-store.com/en_eu/3-lock-leather-white-black-el020005.html', 
    },
    {
        brand: "ILYSM",
        name: "Tabi Sneaker",
        price: "129",
        material: "Textile",
        color: "Black",
        occasion: 'Casual',
        silohuette: 'Sock',
        image: 'images/0065.jpg',
        link: 'https://shop.ilysm.com/collections/tabi-sneakers/products/silk-tabi-shadow-stripe', 
    },
    {
        brand: "Yeezy",
        name: "450",
        price: "200",
        material: "Textile",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'Sock',
        image: 'images/0066.jpg',
        link: 'https://stockx.com/adidas-yeezy-450-cloud-white', 
    },
    {
        brand: "Loro Piana",
        name: "Traveller Walk",
        price: "1025",
        material: "Leather",
        color: "White",
        occasion: 'Casual',
        silohuette: 'low_Minimal',
        image: 'images/0067.jpg',
        link: 'https://us.loropiana.com/en/p/shoes/man/traveller-walk-sneaker-FAI8116?colorCode=100E', 
    },
    {
        brand: "Adidas",
        name: "Ultraboost 21",
        price: "180",
        material: "Textile",
        color: "Multi",
        occasion: 'Active',
        silohuette: 'Runner',
        image: 'images/0068.jpg',
        link: 'https://www.adidas.com/us/ultraboost-21-shoes/FY0377.html', 
    },
    {
        brand: "Keds",
        name: "Royal Lo",
        price: "59.95",
        material: "Canvas",
        color: "Black",
        occasion: 'Casual',
        silohuette: 'Chucks',
        image: 'images/0069.jpg',
        link: 'https://www.keds.com/en/unisex-royal-lo/14318U.html?dwvar_14318U_color=PK54468#cgid=pro-keds&start=1', 
    },
    {
        brand: "Spalwart",
        name: "Smash",
        price: "425",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'low_Minimal',
        image: 'images/0070.jpg',
        link: 'https://spalwart.com/webshop/product/165/1897/smash-low-nappa-ws/1897/7864/', 
    },
    {
        brand: "Nike x Sacai",
        name: "LD Waffle",
        price: "160",
        material: "Textile",
        color: "Black",
        occasion: 'Going Out',
        silohuette: 'Runner',
        image: 'images/0071.jpg',
        link: 'https://stockx.com/nike-ld-waffle-sacai-dark-grey-black-anthracite', 
    },
    {
        brand: "Alexander McQueen",
        name: "Oversized Sneaker",
        price: "540",
        material: "Leather",
        color: "540",
        occasion: 'Going Out',
        silohuette: 'low_Minimal',
        image: 'images/0072.jpg',
        link: 'https://www.alexandermcqueen.com/en-us/sneakers/oversized-sneaker-553770WHGP79061.html', 
    },
    {
        brand: "Visvim",
        name: "Corda-Folk",
        price: "1035",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'low_Minimal',
        image: 'images/0073.jpg',
        link: 'https://shop.visvim.com/0321102002006', 
    },
    {
        brand: "Nike",
        name: "Waffle Trainer 2 SP",
        price: "100",
        material: "Textile",
        color: "Navy",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0074.jpg',
        link: 'nike.com/t/waffle-trainer-2-sp-mens-shoe-MkbSQ4/DB3004-400?nikemt=true&cp=81742485461_search_%7CPRODUCT_GROUP%7CGOOGLE%7C71700000052538341%7CAll_X_X_X_X-Device_X_Nike-FullPrice_X%7C%7Cc&gclsrc=aw.ds&&gclid=Cj0KCQjw1PSDBhDbARIsAPeTqrcKRXGdcjkEoXoHOwNFb1gqDkQrdHruQcC9kxZDNFwRVFw_J6hNSVYaAluQEALw_wcB&gclsrc=aw.ds', 
    },
    {
        brand: "Hoka",
        name: "Bondi 7",
        price: "150",
        material: "Textile",
        color: "Black",
        occasion: 'Active',
        silohuette: 'Runner',
        image: 'images/0075.jpg',
        link: 'https://www.hokaoneone.com/womens-road/bondi-7/192410927722.html?source=shoppingsite_PLA_1110519-BBLC-06.5&kpid=1110519-BBLC-06.5&utm_source=google&utm_medium=pla&gclid=Cj0KCQjw1PSDBhDbARIsAPeTqrfSFhjShtz9nHBepdVTDcWmYFgs5HD0fM2Jkhs4JMcKAfngJaxSZsEaAveuEALw_wcB&gclsrc=aw.ds', 
    },
    {
        brand: "Vans",
        name: "Sk8-Hi",
        price: "70",
        material: "Textile",
        color: "Grey",
        occasion: 'Casual',
        silohuette: 'Skate',
        image: 'images/0076.jpg',
        link: 'https://www.vans.com/shop/shoes-classics-womens-sk8-hi/sk8-hi-tapered-drizzle-true-white', 
    },
    {
        brand: "Christian Louboutin",
        name: "Vieira",
        price: "895",
        material: "Suede",
        color: "Beige",
        occasion: 'Going Out',
        silohuette: 'Skate',
        image: 'images/0077.jpg',
        link: 'https://www.net-a-porter.com/en-us/shop/product/christian-louboutin/vieira-spiked-suede-sneakers/1303519', 
    },
    {
        brand: "Saint Laurent",
        name: "Court Classic",
        price: "595",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'low_Minimal',
        image: 'images/0078.jpg',
        link: 'https://www.ysl.com/en-us/sneakers/court-classic-sl-06-embroidered-sneakers-in-smooth-and-metallic-leather-61135200NA09085.html', 
    },
    {
        brand: "Vibram",
        name: "V-Aqua",
        price: "90",
        material: "Textile",
        color: "Black",
        occasion: 'Active',
        silohuette: 'Sock',
        image: 'images/0079.jpg',
        link: 'https://us.vibram.com/shop/shop-all-products/mens-fivefingers/bestsellers/v-aqua-mens-M73.html?dwvar_M73_color=Black#start=1', 
    },
    {
        brand: "Prada",
        name: "Cotton Canvas Sneaker",
        price: "695",
        material: "Canvas",
        color: "Black",
        occasion: 'Casual',
        silohuette: 'Chucks',
        image: 'images/0080.jpg',
        link: 'https://www.prada.com/us/en/women/shoes/sneakers/products.cotton_canvas_sneakers.1E231M_2OFZ_F057Z_F_035.html', 
    },
    {
        brand: "Asics",
        name: "Gel Kayano 14",
        price: "155",
        material: "Textile",
        color: "Multi",
        occasion: 'Active',
        silohuette: 'Runner',
        image: 'images/0081.jpg',
        link: 'https://www.ssense.com/en-us/women/product/asics/off-white-and-blue-gel-kayano-14-sneakers/6076491', 
    },
    {
        brand: "Adidas",
        name: "N3XT L3V3L",
        price: "180",
        material: "Textile",
        color: "Multi",
        occasion: 'Active',
        silohuette: 'Sock',
        image: 'images/0082.jpg',
        link: 'https://www.adidas.com/us/n3xt-l3v3l-futurenatural-shoes/FX7117.html', 
    },
    {
        brand: "Nike",
        name: "Kyrie 6",
        price: "125",
        material: "Textile",
        color: "Multi",
        occasion: 'Active',
        silohuette: 'Basketball',
        image: 'images/0083.jpg',
        link: 'https://int.stadiumgoods.com/en-us/shopping/kyrie-6-ep-oracle-aqua-cheetah-15209896?ranMID=41568&ranEAID=t*64622QPuc&ranSiteID=t.64622QPuc-w9mcTAYtmJq9HK.xVD2HrQ&utm_medium=affiliate&utm_source=Highsnobiety.com&utm_content=3408659', 
    },
    {
        brand: "Bottega Veneta",
        name: "The Quilt Sneakers",
        price: "880",
        material: "Leather",
        color: "Black",
        occasion: 'Going Out',
        silohuette: 'slip_On',
        image: 'images/0084.jpg',
        link: 'https://www.ssense.com/en-us/women/product/bottega-veneta/black-the-quilt-sneakers/5916131', 
    },
    {
        brand: "R13",
        name: "High Top Sneaker",
        price: "495",
        material: "Canvas",
        color: "Black",
        occasion: 'Going Out',
        silohuette: 'Chucks',
        image: 'images/0085.jpg',
        link: 'https://www.r13denim.com/collections/sneakers/products/high-top-sneaker-1', 
    },
    {
        brand: "Nike",
        name: "Daybreak",
        price: "90",
        material: "Textile",
        color: "Grey",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0086.jpg',
        link: 'https://www.nike.com/t/daybreak-womens-shoe-kM5pxT/CK2351-008?nikemt=true&cp=96413943330_search_%7cPRODUCT_GROUP%7cGOOGLE%7c71700000041489782%7cAll_X_X_X_X-Device_X_Nike-Clearance_X%7c%7cc&gclid=Cj0KCQjw1PSDBhDbARIsAPeTqrcFm_-MBaqomc_9XQIL39JQhxuVZlqTlcohBXCvx-cYTCpVA2dxI0YaArVjEALw_wcB&gclsrc=aw.ds', 
    },
    {
        brand: "APL",
        name: "Techloom Wave",
        price: "225",
        material: "Textile",
        color: "Grey",
        occasion: 'Active',
        silohuette: 'Runner',
        image: 'images/0087.jpg',
        link: 'https://www.athleticpropulsionlabs.com/collections/womens-bestsellers/products/womens-techloom-wave-heather-grey-black-white', 
    },
    {
        brand: "SeaVees",
        name: "Hermosa",
        price: "78",
        material: "Canvas",
        color: "Black",
        occasion: 'Casual',
        silohuette: 'Skate',
        image: 'images/0088.jpg',
        link: 'https://www.seavees.com/products/mens-hermosa-sneaker-classic-black', 
    },
    {
        brand: "Swear",
        name: "Air Revive Xtra",
        price: "210",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'Sock',
        image: 'images/0089.jpg',
        link: 'https://www.farfetch.com/shopping/women/swear-air-revive-xtra-sneakers-item-16133512.aspx?storeid=9939', 
    },
    {
        brand: "Stepney Workers Club",
        name: "Varden S-Strike",
        price: "135",
        material: "Canvas",
        color: "Black",
        occasion: 'Casual',
        silohuette: 'Skate',
        image: 'images/0090.jpg',
        link: 'https://www.stepneyworkersclub.com/varden-s-strike-canvas-black.html', 
    },
    {
        brand: "Yeezy",
        name: "500",
        price: "220",
        material: "Textile",
        color: "Grey",
        occasion: 'Casual',
        silohuette: 'Basketball',
        image: 'images/0091.jpg',
        link: 'https://stockx.com/adidas-yeezy-500-high-slate?utm_source=af&utm_medium=imp&utm_campaign=10078&impactSiteId=wU42APRD-xyLUtYwUx0Mo37kUkB0k1Sfs2A-S80&clickid=wU42APRD-xyLUtYwUx0Mo37kUkB0k1Sfs2A-S80&utm_term=wU42APRD-xyLUtYwUx0Mo37kUkB0k1Sfs2A-S80&utm_content=one37pm.com_530344&irgwc=1', 
    },
    {
        brand: "Rick Owens",
        name: "Phlegethon",
        price: "1,145",
        material: "Leather",
        color: "Black",
        occasion: 'Going Out',
        silohuette: 'Chucks',
        image: 'images/0092.jpg',
        link: 'https://www.rickowens.eu/en/US/men/products/ru21s6890lpo-911', 
    },
    {
        brand: "Nike",
        name: "Air Huarache",
        price: "110",
        material: "Textile",
        color: "White",
        occasion: 'Active',
        silohuette: 'Runner',
        image: 'images/0093.jpg',
        link: 'https://www.nike.com/t/air-huarache-mens-shoe-eoToq9X2/318429-111', 
    },
    {
        brand: "Shoes Like Pottery",
        name: "01JP High",
        price: "149",
        material: "Canvas",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Chucks',
        image: 'images/0094.jpg',
        link: 'https://www.endclothing.com/us/shoes-like-pottery-01jp-high-sneaker-12331817.html?173=uk-6&utm_source=google_surfaces&utm_medium=cpc&utm_campaign=google_surface_us&gclid=Cj0KCQjw1PSDBhDbARIsAPeTqrfPhYSOFI_nQ9Rw-TioV228c6lzVX3EkqMfCTjC5Bl4mHy9BCbRIsQaAmgnEALw_wcB', 
    },
    {
        brand: "Prada",
        name: "Cloudbust Thunder",
        price: "990",
        material: "Textile",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'Runner',
        image: 'images/0095.jpg',
        link: 'https://www.prada.com/us/en/men/shoes/sneakers/products.cloudbust_thunder_technical_fabric_sneakers.2EG293_3KZU_F0009.html', 
    },
    {
        brand: "Gucci x Disney",
        name: "Rhyton",
        price: "890",
        material: "Leather",
        color: "White",
        occasion: 'Going Out',
        silohuette: 'Runner',
        image: 'images/0096.jpg',
        link: 'https://www.gucci.com/us/en/pr/men/shoes-for-men/sneakers-for-men/mens-disney-x-gucci-rhyton-sneaker-p-601370DRW009522', 
    },
    {
        brand: "Nike",
        name: "ACG Mountain Fly",
        price: "220",
        material: "Textile",
        color: "Khaki",
        occasion: 'Active',
        silohuette: 'Sock',
        image: 'images/0097.jpg',
        link: 'https://www.nike.com/launch/t/acg-mountain-fly-khaki', 
    },
    {
        brand: "Raf Simons",
        name: "Cylon 21",
        price: "530",
        material: "Textile",
        color: "Black",
        occasion: 'Going Out',
        silohuette: 'Runner',
        image: 'images/0098.jpg',
        link: 'https://www.highsnobiety.com/shop/product/raf-simons-cylon-grey/', 
    },
    {
        brand: "Sunnei",
        name: "White Leather Dreamy",
        price: "467",
        material: "Leather",
        color: "White",
        occasion: 'Casual',
        silohuette: 'Basketball',
        image: 'images/0099.jpg',
        link: 'https://sunnei.it/products/special-dre01-white-leather', 
    },
    {
        brand: "Merrell",
        name: "Long Sky",
        price: "130",
        material: "Textile",
        color: "White",
        occasion: 'Active',
        silohuette: 'Runner',
        image: 'images/0100.jpg',
        link: 'https://www.brownsfashion.com/shopping/white-long-sky-mesh-sneakers-15655694?utm_source=google&utm_medium=shopping-organic&utm_campaign=us-en-usd&gclid=Cj0KCQjw1PSDBhDbARIsAPeTqreGTHEXtK5kKo4FMP_7H984rHmCAnQ4HRo7cJ7eiH1WjK7Jroz2Ym0aAjZvEALw_wcB', 
    },
    // {
    //     brand: "",
    //     name: "",
    //     price: "",
    //     material: "",
    //     color: "",
    //     occasion: '',
    //     silohuette: '',
    //     image: '',
    //     link: '', 
    // },
]

// Pull DOM elements

let imageViewer = document.getElementById("imageViewer");
let brandDisplay = document.getElementById("brandDisplay");
let nameDisplay = document.getElementById("nameDisplay");
let priceDisplay = document.getElementById("priceDisplay");

// call a random image for viewer

let randomStart = Math.floor(Math.random() * sneakers.length);

console.log(randomStart);

// add random first image to image viewer

imageViewer.src = sneakers[randomStart].image;
brandDisplay.textContent += sneakers[randomStart].brand;
nameDisplay.textContent += sneakers[randomStart].name;
priceDisplay.textContent += sneakers[randomStart].price;

// remove first image from array

console.log(sneakers.length)

let sneakersPicked = sneakers.splice(randomStart, 1);

// pull buttons from DOM

const priceButton = document.querySelector('#price');
const occasionButton = document.querySelector('#occasion');
const materialButton = document.querySelector('#material');
const styleButton = document.querySelector('#style');

// add event listeners

priceButton.addEventListener('click', price);

// functions for selecting comparable images

console.log(sneakersPicked.length)

console.log(sneakers.length)

function price(){
    let cost = sneakersPicked[sneakersPicked.length - 1].price
    console.log(cost)

    let random = Math.floor(Math.random() * sneakers.length);

    if (random.price < cost + 50 & random.price > cost - 50) {
        sneakersPicked += sneakers.splice(random, 1);
    } else {
        let x = true;
        while (x = true) {
            random = Math.floor(Math.random() * sneakers.length);
            if (random.price < cost + 50 & random.price > cost - 50) {
                x = false;
            } else {
                x = true;
            }
        }
        sneakersPicked += sneakers.splice(random, 1);
    }

    imageViewer.src = sneakers[random].image;
    brandDisplay.textContent += sneakers[random].brand;
    nameDisplay.textContent += sneakers[random].name;
    priceDisplay.textContent += sneakers[random].price;

    priceButton.disabled = true
}