const sneakers = [
    {
        brand: "Nike",
        name: "Space Hippie 04",
        price: 130,
        // how can i have multiple, seperately referenceable entries?
        material: 'Synthetic',
        color: 'grey',
        occasion: 'Running',
        silohuette: 'Runner',
        // source: '?' doesn't appear to be easily accessible
        image: 'images/0001.jpg',
        link: 'https://www.nike.com/t/space-hippie-04-mens-shoe-gGWDLk/CZ6398-002?nikemt=true&cp=96413943330_search_%7cPRODUCT_GROUP%7cGOOGLE%7c71700000041489782%7cAll_X_X_X_X-Device_X_Nike-Clearance_X%7c%7cc&gclid=Cj0KCQjwmIuDBhDXARIsAFITC_7aVU7xKEntm8ZG8oHtFXgdkbxl4B6j8JYxGhoSMxdvEIsm2MLOIlcaAn_zEALw_wcB&gclsrc=aw.ds',
    },
    {
        brand: "Balenciaga",
        name: "Triple S Clear Sole",
        price: 1090,
        material: "Synthetic",
        color: "Black",
        occasion: 'Formal',
        silohuette: 'Runner',
        image: 'images/0002.jpg',
        link: 'https://www.balenciaga.com/en-us/triple-s-clear-sole-black-544351W2FB11000.html', 
    },
    {
        brand: "Off-White",
        name: "Canvas Vulcanized Sneakers",
        price: 255,
        material: "Cotton",
        color: "White",
        occasion: 'Street',
        silohuette: 'Skate',
        image: 'images/0003.jpg',
        link: 'https://www.ssense.com/en-us/women/product/off-white/white-canvas-vulcanized-sneakers/6281631', 
    },
    {
        brand: "Golden Goose",
        name: "Super-Star",
        price: 560,
        material: "Suede",
        color: "Brown",
        occasion: 'Formal',
        silohuette: 'low-Minimal',
        image: 'images/0004.jpg',
        link: 'https://www.goldengoose.com/us/en/leopard-print-suede-super-star-sneakers-cod-GWF00101.F001472.81116.html', 
    },
    {
        brand: "New Balance",
        name: "993",
        price: 184.99,
        material: "Synthetic",
        color: "Grey",
        occasion: 'Formal',
        silohuette: 'Runner',
        image: 'images/0005.jpg',
        link: 'https://www.newbalance.com/pd/mens-made-in-us-993/MR993V1-M.html', 
    },
    {
        brand: "Adidas",
        name: "Stan Smith",
        price: 85,
        material: "Leather",
        color: "White",
        occasion: 'Formal',
        silohuette: 'low-Minimal',
        image: 'images/0006.jpg',
        link: 'https://www.adidas.com/us/stan-smith-shoes/FX5502.html', 
    },
    {
        brand: "Nike",
        name: "Blazer Mid '77",
        price: 100,
        material: "Leather",
        color: "White",
        occasion: 'Street',
        silohuette: 'Basketball',
        image: 'images/0007.jpg',
        link: 'https://www.nike.com/t/blazer-mid-77-essential-womens-shoe-25h71W/CZ1055-114?nikemt=true&cp=71606177307_search_%7CPRODUCT_GROUP%7CGOOGLE%7C71700000041489779%7CAll_X_X_X_X-Device_X_Nike-FullPrice_X%7C%7Cc&gclsrc=aw.ds&&gclid=CjwKCAjwjbCDBhAwEiwAiudByxnOZVR-u59tR4I8rEl8uHmlTXtxWTvaH7uuImenppevmqtN-_NXnBoCN7UQAvD_BwE&gclsrc=aw.ds', 
    },
    {
        brand: "Vans",
        name: "Old Skool",
        price: 60,
        material: "Canvas",
        color: "Black",
        occasion: 'Casual',
        silohuette: 'Skate',
        image: 'images/0008.png',
        link: 'https://www.vans.com/shop/old-skool-black-white?utm_id=go_cmp-191532173_adg-26624222573_ad-95842386413_pla-866008078493_dev-c_ext-_prd-700053803770_mca-8181713_sig-CjwKCAjwjbCDBhAwEiwAiudByzJZruajq9SjI2OWs6qa5fyyVYE1I9wg2zufqghhya013cPJtkSZyhoC1SUQAvD_BwE&utm_source=google&gclid=CjwKCAjwjbCDBhAwEiwAiudByzJZruajq9SjI2OWs6qa5fyyVYE1I9wg2zufqghhya013cPJtkSZyhoC1SUQAvD_BwE', 
    },
    {
        brand: "Converse",
        name: "Chuck Taylor All Star",
        price: 55,
        material: "Canvas",
        color: "White",
        occasion: 'Casual',
        silohuette: 'low-Minimal',
        image: 'images/0009.jpg',
        link: 'https://www.converse.com/shop/p/chuck-taylor-all-star-unisex-low-top-shoe/M7652.html?dwvar_M7652_color=optical%20white&styleNo=M7652&cgid=womens-best-sellers', 
    },
    {
        brand: "Air Jordan",
        name: "Jordan 1 Retro High",
        price: 160,
        material: "Leather",
        color: "Red",
        occasion: 'Going Out',
        silohuette: 'Basketball',
        image: 'images/0010.jpg',
        link: 'https://stockx.com/air-jordan-1-retro-high-satin-black-toe-w', 
    },
    {
        brand: "Nike",
        name: "Air Max 90",
        price: 120,
        material: "Synthetic",
        color: "Pink",
        occasion: 'Casual',
        silohuette: 'Runner',
        image: 'images/0011.jpg',
        link: '', 
    },
    {
        brand: "Reebok",
        name: "Club C 85",
        price: 70,
        material: "Leather",
        color: "White",
        occasion: 'Casual',
        silohuette: 'low-Minimal',
        image: 'images/0012.jpg',
        link: 'https://www.reebok.com/us/club-c-85-model-vintage-womens-shoes/BS8242.html', 
    },
    // {
    //     brand: "",
    //     name: "",
    //     price: "",
    //     material: "",
    //     color: "",
    //     occasion: '',
    //     silohuette: '',
    //     image: '',
    //     link: '', 
    // },
]